export const CREATE_POST_SUCCESS = 'POST/CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'POST/CREATE_POST_FAILURE';

export const FETCH_POSTS_REQUEST = 'POST/FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'POST/FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'POST/FETCH_POSTS_FAILURE';
